### ISSUE TITLE
VM: przykładowe programy nie działają

### ISSUE THREAD

**Issue by bartekpacia** [gynvael/zrozumiec-programowanie#6]
Hej,

Niestety żaden z przykładowych programów na VM-kę nie działa. Dla każdego uruchomienia otrzymuję poniższe logi:

```
$ python vm.py ./upper.nasm
The virtual machine entered an erroneous state and is terminating.
Register values at termination:
  r0 = 0
  r1 = 0
  r2 = 0
  r3 = 0
  r4 = 0
  r5 = 0
  r6 = 0
  r7 = 0
  r8 = 0
  r9 = 0
  r10 = 0
  r11 = 0
  r12 = 0
  r13 = 0
  r14 = 34
  r15 = ffffffff
```

Podejrzewałem, że może coś zostało zepsute w #5, dlatego przełączyłem się na Pythona 2.7.18 i na commit [73235f5](https://github.com/gynvael/zrozumiec-programowanie/commit/73235f54c31ce5e50a9c4a7afacafe481ba2b74b), ale problem dalej występuje.

### Dodatkowe info

macOS Ventura (13.0.1)

```
$ python --version
Python 3.10.5
```

**Comment by kamilos-dev** [comment]
Najpierw musisz skompilować plik .nasm `nasm upper.nasm` a dopiero potem `python upper`.

**Comment by bartekpacia** [comment]
@szyn33k Dzięki za odpowiedź. Niestety wywołanie `nasm upper.nasm`, a następnie uruchomienie `python vm.py ./upper.nasm` dalej mi nie działa:


```
Register values at termination:
  r0 = 0
  r1 = 0
  r2 = 0
  r3 = 0
  r4 = 0
  r5 = 0
  r6 = 0
  r7 = 0
  r8 = 0
  r9 = 0
  r10 = 0
  r11 = 0
  r12 = 0
  r13 = 0
  r14 = 34
  r15 = ffffffff
```


```
$ nasm --version
NASM version 2.16.01 compiled on Dec 23 2022
```

```
$ python3 --version
Python 3.11.1
```

### Edit

Mój błąd! 

Trzeba zrobić `python3 vm.py upper`, a nie `python3 vm.py upper.nasm` :D
